name: Validate Changes

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Code Checks
        run: npm run lint

      - name: Run Formatting Checks
        run: npm run format

  lint_commits:
    name: Validate Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci

      # https://github.com/wagoid/commitlint-github-action
      - name: Validate commits differing from the default branch
        # Lint only commit range that differs from origin default branch, assuming current branch is ahead
        # run: "$(npm bin)/commitlint -f origin/<base branch>~<number of commits before to include> -t <branch to compare> -V"
        run: "npm exec -- commitlint -f origin/${{ github.event.repository.default_branch }}~0 -t HEAD -V"

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npm exec -- commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npm exec -- commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
